export const authConstants = {
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAILED : 'LOGIN_FAILED',
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    LOGOUT_FAILED : 'LOGOUT_FAILED'
}
export const signupConstants = {
    SIGNUP_REQUEST : 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS : 'SIGNUP_SUCCESS',
    SIGNUP_FAILED : 'SIGNUP_FAILED',
}
export const productConstants = {
    PRODUCT_CATEGORY_REQUEST : 'PRODUCT_CATEGORY_REQUEST',
    PRODUCT_CATEGORY_SUCCESS : 'PRODUCT_CATEGORY_SUCCESS',
    PRODUCT_CATEGORY_FAILED : 'PRODUCT_CATEGORY_FAILED',
}
export const categoryConstants = {
    ADD_CATEGORY_REQUEST : 'ADD_CATEGORY_REQUEST',
    ADD_CATEGORY_SUCCESS : 'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAILED : 'ADD_CATEGORY_FAILED',
}
export const addProducts = {
    ADD_PRODUCT_REQUEST : 'ADD_PRODUCT_REQUEST',
    ADD_PRODUCT_SUCCESS : 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILED : 'ADD_PRODUCT_FAILED',
}